language: ruby
bundler_args: --without development
before_script:
  - bundle exec rake validate_ruby_syntax
  - bundle exec rake check_line_endings
  - bundle exec rake syntax
  - bundle exec rake lint
script:
  - bundle exec rake spec SPEC_OPTS='--format documentation'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.6.0"
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0"
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.8.7
    - env: PUPPET_GEM_VERSION="~> 2.6.0"
    - env: PUPPET_GEM_VERSION="~> 2.7.0"
    - env: PUPPET_GEM_VERSION="~> 3.0.0"
    - env: PUPPET_GEM_VERSION="~> 3.1.0"
    - env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
    - env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
    - env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.4.0"
notifications:
  email: false